name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-server:
    runs-on: ubuntu-latest

    env:
      working-directory: ./

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Pull dependencies
      run: npm ci
      working-directory: ${{ env.working-directory }}
    - name: Build
      run: npm run build --if-present
      working-directory: ${{ env.working-directory }}

  build-frontend:
    runs-on: ubuntu-latest

    env:
      working-directory: ./www

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Pull dependencies
      run: npm ci
      working-directory: ${{ env.working-directory }}
    - name: Build
      run: npm run build --if-present
      working-directory: ${{ env.working-directory }}
